version: '3'

services:

  mysql-db:
    container_name: mysql        # 指定容器的名称
    image: mysql:8.0                   # 指定镜像和版本
    ports:
      - "3306:3306"
    restart: 'always'
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - "./mysql/data:/var/lib/mysql"           # 挂载数据目录